jobs:
- job: linux
  pool: {vmImage: 'Ubuntu-16.04'}
  variables:
    upload: $(Build.ArtifactStagingDirectory)
  steps:
    - script: |
        sudo apt-get update
        sudo apt-get install gfortran
      displayName: Install gfortran
    - bash: |
        git submodule update --init --recursive --remote
        mkdir build
        cd build
        cmake ..
        make all coin-versions -j4
        make test
        mkdir -p $UPLOAD/linux
        cp -r * $UPLOAD/linux
      displayName: Build package
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: '$(Build.ArtifactStagingDirectory)'}
- job: macos
  pool: {vmImage: 'macOS-10.13'}
  variables:
    upload: $(Build.ArtifactStagingDirectory)
  steps:
    - script: |
        brew install gcc
      displayName: Install gcc (installs gfortran too)
    - bash: |
        git submodule update --init --recursive --remote
        mkdir build
        cd build
        cmake ..
        make all coin-versions -j4
        make test
        mkdir -p $UPLOAD/macos
        cp -r * $UPLOAD/macos
      displayName: Build package
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: '$(Build.ArtifactStagingDirectory)'}
- job: windows
  pool: {vmImage: 'vs2017-win2016'}
  variables:
    upload: $(Build.ArtifactStagingDirectory)
  steps:
    - bash: |
        git submodule update --init --recursive --remote
        mkdir build
        cd build
        cmake .. -G"MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND"
        cmake --build . --parallel 4
        ctest
        mkdir -p $UPLOAD/windows
        cp -r * $UPLOAD/windows
      displayName: Build package
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: '$(Build.ArtifactStagingDirectory)'}
